### PR TITLE
REDC-6774: prepare sourcepoint cmp for migration

### PR DESCRIPTION
**Pull request by dmitriy-grablyov**
@dmitriy-grablyov 

https://axelspringer.atlassian.net/browse/REDC-6774

Apart from standard procedures I also performed some cleanup.
- removed everything related to CAE scripts. They've been broken and disabled a year ago and it didn't seem to be a problem at all. Although the fix is very easy (to treat Terser output as promise), I don't think it is worth the maintenance effort due to reason mentioned above.
- removed every mention of storybook. Storybook deps here seem very old, the usage on the pipeline is questionable (on every release creation, and not on PR). Anyway I did not even find a single run in the history. For visual testing there are still 'playground' scripts that remain and after monorepo integration there will be a direct visibility in the apps. On the other hand removing storybook deps dramatically decreases the number of npm security alerts, critical 20->6, high 37->17, moderate 36->13.

### CODE REVIEW

**Comment by preventdefault** [comment]
I would say, we could remove the playground as well, since (you mentioned it) after the migration, the implementation could be tested directly in the apps.

**Comment by dmitriy-grablyov** [comment]
@preventdefault I am not completely sure on this part. Same way I wanted to completely remove storybook from shared components, but it was not a solution for Aykut, he sais it is almost impossible to test different variants of the same component in the app. 

Release configuration will be removed during the actual migration, not now. If somebody needs to rollout the fix for cmp, I don't want this migration process to be a blocker for it.

**Comment by preventdefault** [comment]
Ok, i you have some doubts, then leave it and remove it at a later point. No problem at all.

**Comment by m31415** [comment]
Just a minor thing, but if we remove Storybook from this package we should adjust the jest.config, I think `stories` should be removed.

`  collectCoverageFrom: ['**/*.{js,ts,vue}', '!**/*.stories.js', '!**/*.d.ts'],`

**Review by m31415 — APPROVED** [review]

**Pull request merged**
